In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
data = pd.read_csv('data/Census_UHI_US_Urbanized_vegetation_albedo_CUHI_SUHI.csv')

In [3]:
data.head()

,system:index,AT_rur_day_summer,AT_rur_night_summer,AT_urb_day_CT_act_summer,AT_urb_day_all_summer,AT_urb_night_CT_act_summer,AT_urb_night_all_summer,Albedo,Albedo_Built,Albedo_Built_all,Albedo_Grass,Albedo_Grass_all,Albedo_Tree,Albedo_Tree_all,Albedo_all,Area,Census_geoid,DEM_rur,DEM_urb_CT,DEM_urb_CT_act,DEM_urb_all,ESABuilt,ESABuilt_all,ESAGrass,ESAGrass_all,ESATree,ESATree_all,LST_rur_day_summer,LST_rur_night_summer,LST_urb_day_CT_act_summer,LST_urb_day_all_summer,LST_urb_night_CT_act_summer,LST_urb_night_all_summer,Urban_geoid,Urban_name,Urban_name_extended,.geo
0,00000000000000000132,34.924404,21.757747,35.112454,35.016955,21.933739,21.85244,0.214670,0.222724,0.227048,0.215284,0.204732,0.180942,0.173744,0.212203,3.612190e+06,48441011400,535.962751,531.262001,531.262001,533.762669,1.923120e+06,4.970526e+07,3.074373e+05,4.279068e+07,7.771083e+05,2.264740e+07,41.7423,22.614651,43.351823,42.363243,23.277403,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}"
1,00000000000000000133,34.924404,21.757747,34.978955,35.016955,21.911980,21.85244,0.221502,0.248659,0.227048,0.208602,0.204732,0.164859,0.173744,0.212203,7.995815e+06,48441012200,535.962751,529.449501,532.223446,533.762669,1.598146e+06,4.970526e+07,3.646100e+06,4.279068e+07,1.322474e+06,2.264740e+07,41.7423,22.614651,41.693683,42.363243,22.925598,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}"
2,00000000000000000134,34.924404,21.757747,34.925510,35.016955,21.900347,21.85244,0.217811,0.247611,0.227048,0.222031,0.204732,0.154968,0.173744,0.212203,1.301622e+06,48441012100,535.962751,531.698485,531.698485,533.762669,3.897641e+05,4.970526e+07,5.920586e+05,4.279068e+07,2.398845e+05,2.264740e+07,41.7423,22.614651,40.512643,42.363243,22.430844,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}"
3,00000000000000000135,34.924404,21.757747,35.190528,35.016955,22.110893,21.85244,0.235294,0.243688,0.227048,0.217764,0.204732,0.189559,0.173744,0.212203,1.827807e+06,48441011900,535.962751,529.895505,529.895505,533.762669,9.567481e+05,4.970526e+07,1.491961e+05,4.279068e+07,3.368867e+05,2.264740e+07,41.7423,22.614651,43.857052,42.363243,23.956061,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}"
4,00000000000000000323,34.924404,21.757747,35.108325,35.016955,22.096334,21.85244,0.215404,0.220232,0.227048,0.217527,0.204732,0.188800,0.173744,0.212203,2.746964e+06,48441012300,535.962751,538.201497,538.201497,533.762669,1.386262e+06,4.970526e+07,4.748822e+05,4.279068e+07,4.949957e+05,2.264740e+07,41.7423,22.614651,43.410609,42.363243,23.800659,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}"

In [4]:
len(data)

55871

In [5]:
meta = pd.read_csv('data/Census_UHI_US_Urbanized_climzone_metadata.csv')

In [6]:
meta.rename(columns={'.geo': 'LatLon'},inplace=True)

In [7]:
meta.head()

,system:index,Clim_zone,Coastal?,Urban_name,LatLon
0,00000000000000000000,Arid,False,"Denver--Aurora, CO","{""type"":""Point"",""coordinates"":[-104.9116864828..."
1,00000000000000000001,Snow,False,"Des Moines, IA","{""type"":""Point"",""coordinates"":[-93.64925307140..."
2,00000000000000000002,Snow,False,"Detroit, MI","{""type"":""Point"",""coordinates"":[-83.21850259851..."
3,00000000000000000003,Temperate,False,"Dothan, AL","{""type"":""Point"",""coordinates"":[-85.43345475538..."
4,00000000000000000004,Snow,False,"Dover--Rochester, NH--ME","{""type"":""Point"",""coordinates"":[-70.91964071905..."

In [8]:
data = data.merge(meta[['Clim_zone', 'Coastal?', 'Urban_name', 'LatLon']], how='left', on='Urban_name')

In [9]:
len(data)

55871

In [10]:
data.head()

,system:index,AT_rur_day_summer,AT_rur_night_summer,AT_urb_day_CT_act_summer,AT_urb_day_all_summer,AT_urb_night_CT_act_summer,AT_urb_night_all_summer,Albedo,Albedo_Built,Albedo_Built_all,Albedo_Grass,Albedo_Grass_all,Albedo_Tree,Albedo_Tree_all,Albedo_all,Area,Census_geoid,DEM_rur,DEM_urb_CT,DEM_urb_CT_act,DEM_urb_all,ESABuilt,ESABuilt_all,ESAGrass,ESAGrass_all,ESATree,ESATree_all,LST_rur_day_summer,LST_rur_night_summer,LST_urb_day_CT_act_summer,LST_urb_day_all_summer,LST_urb_night_CT_act_summer,LST_urb_night_all_summer,Urban_geoid,Urban_name,Urban_name_extended,.geo,Clim_zone,Coastal?,LatLon
0,00000000000000000132,34.924404,21.757747,35.112454,35.016955,21.933739,21.85244,0.214670,0.222724,0.227048,0.215284,0.204732,0.180942,0.173744,0.212203,3.612190e+06,48441011400,535.962751,531.262001,531.262001,533.762669,1.923120e+06,4.970526e+07,3.074373e+05,4.279068e+07,7.771083e+05,2.264740e+07,41.7423,22.614651,43.351823,42.363243,23.277403,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504..."
1,00000000000000000133,34.924404,21.757747,34.978955,35.016955,21.911980,21.85244,0.221502,0.248659,0.227048,0.208602,0.204732,0.164859,0.173744,0.212203,7.995815e+06,48441012200,535.962751,529.449501,532.223446,533.762669,1.598146e+06,4.970526e+07,3.646100e+06,4.279068e+07,1.322474e+06,2.264740e+07,41.7423,22.614651,41.693683,42.363243,22.925598,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504..."
2,00000000000000000134,34.924404,21.757747,34.925510,35.016955,21.900347,21.85244,0.217811,0.247611,0.227048,0.222031,0.204732,0.154968,0.173744,0.212203,1.301622e+06,48441012100,535.962751,531.698485,531.698485,533.762669,3.897641e+05,4.970526e+07,5.920586e+05,4.279068e+07,2.398845e+05,2.264740e+07,41.7423,22.614651,40.512643,42.363243,22.430844,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504..."
3,00000000000000000135,34.924404,21.757747,35.190528,35.016955,22.110893,21.85244,0.235294,0.243688,0.227048,0.217764,0.204732,0.189559,0.173744,0.212203,1.827807e+06,48441011900,535.962751,529.895505,529.895505,533.762669,9.567481e+05,4.970526e+07,1.491961e+05,4.279068e+07,3.368867e+05,2.264740e+07,41.7423,22.614651,43.857052,42.363243,23.956061,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504..."
4,00000000000000000323,34.924404,21.757747,35.108325,35.016955,22.096334,21.85244,0.215404,0.220232,0.227048,0.217527,0.204732,0.188800,0.173744,0.212203,2.746964e+06,48441012300,535.962751,538.201497,538.201497,533.762669,1.386262e+06,4.970526e+07,4.748822e+05,4.279068e+07,4.949957e+05,2.264740e+07,41.7423,22.614651,43.410609,42.363243,23.800659,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504..."

## Calculate Urban Heat Anomalies
We can calculate the tree fraction, grass fraction, etc. by dividing the tree areas by the area column, which is for area of the census tract.

In [11]:
data['CUHI_day_summer'] = data['AT_urb_day_CT_act_summer'] - data['AT_rur_day_summer']
data['CUHI_night_summer'] = data['AT_urb_night_CT_act_summer'] - data['AT_rur_night_summer']
data['SUHI_day_summer'] = data['LST_urb_day_CT_act_summer'] - data['LST_rur_day_summer']
data['SUHI_night_summer'] = data['LST_urb_night_CT_act_summer'] - data['LST_rur_night_summer']

In [12]:
cols = ['ESABuilt', 'ESAGrass', 'ESATree']
for col in cols:
    data[col+'_Area'] = data[col] / data['Area']

In [13]:
data.head()

,system:index,AT_rur_day_summer,AT_rur_night_summer,AT_urb_day_CT_act_summer,AT_urb_day_all_summer,AT_urb_night_CT_act_summer,AT_urb_night_all_summer,Albedo,Albedo_Built,Albedo_Built_all,Albedo_Grass,Albedo_Grass_all,Albedo_Tree,Albedo_Tree_all,Albedo_all,Area,Census_geoid,DEM_rur,DEM_urb_CT,DEM_urb_CT_act,DEM_urb_all,ESABuilt,ESABuilt_all,ESAGrass,ESAGrass_all,ESATree,ESATree_all,LST_rur_day_summer,LST_rur_night_summer,LST_urb_day_CT_act_summer,LST_urb_day_all_summer,LST_urb_night_CT_act_summer,LST_urb_night_all_summer,Urban_geoid,Urban_name,Urban_name_extended,.geo,Clim_zone,Coastal?,LatLon,CUHI_day_summer,CUHI_night_summer,SUHI_day_summer,SUHI_night_summer,ESABuilt_Area,ESAGrass_Area,ESATree_Area
0,00000000000000000132,34.924404,21.757747,35.112454,35.016955,21.933739,21.85244,0.214670,0.222724,0.227048,0.215284,0.204732,0.180942,0.173744,0.212203,3.612190e+06,48441011400,535.962751,531.262001,531.262001,533.762669,1.923120e+06,4.970526e+07,3.074373e+05,4.279068e+07,7.771083e+05,2.264740e+07,41.7423,22.614651,43.351823,42.363243,23.277403,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.188050,0.175992,1.609523,0.662751,0.532397,0.085111,0.215135
1,00000000000000000133,34.924404,21.757747,34.978955,35.016955,21.911980,21.85244,0.221502,0.248659,0.227048,0.208602,0.204732,0.164859,0.173744,0.212203,7.995815e+06,48441012200,535.962751,529.449501,532.223446,533.762669,1.598146e+06,4.970526e+07,3.646100e+06,4.279068e+07,1.322474e+06,2.264740e+07,41.7423,22.614651,41.693683,42.363243,22.925598,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.054552,0.154233,-0.048617,0.310947,0.199873,0.456001,0.165396
2,00000000000000000134,34.924404,21.757747,34.925510,35.016955,21.900347,21.85244,0.217811,0.247611,0.227048,0.222031,0.204732,0.154968,0.173744,0.212203,1.301622e+06,48441012100,535.962751,531.698485,531.698485,533.762669,3.897641e+05,4.970526e+07,5.920586e+05,4.279068e+07,2.398845e+05,2.264740e+07,41.7423,22.614651,40.512643,42.363243,22.430844,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.001106,0.142600,-1.229657,-0.183807,0.299445,0.454862,0.184297
3,00000000000000000135,34.924404,21.757747,35.190528,35.016955,22.110893,21.85244,0.235294,0.243688,0.227048,0.217764,0.204732,0.189559,0.173744,0.212203,1.827807e+06,48441011900,535.962751,529.895505,529.895505,533.762669,9.567481e+05,4.970526e+07,1.491961e+05,4.279068e+07,3.368867e+05,2.264740e+07,41.7423,22.614651,43.857052,42.363243,23.956061,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.266125,0.353146,2.114752,1.341409,0.523440,0.081626,0.184312
4,00000000000000000323,34.924404,21.757747,35.108325,35.016955,22.096334,21.85244,0.215404,0.220232,0.227048,0.217527,0.204732,0.188800,0.173744,0.212203,2.746964e+06,48441012300,535.962751,538.201497,538.201497,533.762669,1.386262e+06,4.970526e+07,4.748822e+05,4.279068e+07,4.949957e+05,2.264740e+07,41.7423,22.614651,43.410609,42.363243,23.800659,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.183921,0.338587,1.668309,1.186008,0.504653,0.172875,0.180197

In [15]:
data.groupby('Clim_zone')[['CUHI_day_summer', 'CUHI_night_summer', 'SUHI_day_summer', 'SUHI_night_summer']].mean()

,CUHI_day_summer,CUHI_night_summer,SUHI_day_summer,SUHI_night_summer
Clim_zone,,,,
Arid,0.141129,0.462547,0.404254,0.708871
Snow,0.217646,0.263623,2.093398,0.743501
Temperate,0.303357,0.336818,2.095694,0.691979
Tropical,0.196556,0.330725,2.490008,0.640509

## Add Median Income Data

In [16]:
income_df = pd.read_csv('data/ACSDT5Y2017.B20018_2025-02-04T152116/ACSDT5Y2017.B20018-Data.csv', skiprows=1)
income_df['Census_geoid'] = income_df['Geography'].str[9:]
income_df['Census_geoid'] = income_df['Census_geoid'].astype('int64')
income_df.rename(columns={'Estimate!!Median earnings in the past 12 months (in 2017 inflation-adjusted dollars)': 'Median Income'}, inplace=True)

data = data.merge(income_df[['Census_geoid', 'Median Income']], how='left', on='Census_geoid')

In [17]:
data.loc[data['Median Income'] == '-', 'Median Income'] = np.nan

data['Median Income'] = data['Median Income'].str.replace('+', '', regex=True)
data['Median Income'] = data['Median Income'].str.replace('-', '', regex=True)
data['Median Income'] = data['Median Income'].str.replace(',', '', regex=True)

# Fill null values with a temporary placeholder
data['Median Income'] = data['Median Income'].fillna(-999)

# Convert to integer
data['Median Income'] = data['Median Income'].astype('int64')

# Set the placeholder back to nulls
data['Median Income'] = data['Median Income'].replace(-999, np.nan)

In [18]:
data.head()

,system:index,AT_rur_day_summer,AT_rur_night_summer,AT_urb_day_CT_act_summer,AT_urb_day_all_summer,AT_urb_night_CT_act_summer,AT_urb_night_all_summer,Albedo,Albedo_Built,Albedo_Built_all,Albedo_Grass,Albedo_Grass_all,Albedo_Tree,Albedo_Tree_all,Albedo_all,Area,Census_geoid,DEM_rur,DEM_urb_CT,DEM_urb_CT_act,DEM_urb_all,ESABuilt,ESABuilt_all,ESAGrass,ESAGrass_all,ESATree,ESATree_all,LST_rur_day_summer,LST_rur_night_summer,LST_urb_day_CT_act_summer,LST_urb_day_all_summer,LST_urb_night_CT_act_summer,LST_urb_night_all_summer,Urban_geoid,Urban_name,Urban_name_extended,.geo,Clim_zone,Coastal?,LatLon,CUHI_day_summer,CUHI_night_summer,SUHI_day_summer,SUHI_night_summer,ESABuilt_Area,ESAGrass_Area,ESATree_Area,Median Income
0,00000000000000000132,34.924404,21.757747,35.112454,35.016955,21.933739,21.85244,0.214670,0.222724,0.227048,0.215284,0.204732,0.180942,0.173744,0.212203,3.612190e+06,48441011400,535.962751,531.262001,531.262001,533.762669,1.923120e+06,4.970526e+07,3.074373e+05,4.279068e+07,7.771083e+05,2.264740e+07,41.7423,22.614651,43.351823,42.363243,23.277403,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.188050,0.175992,1.609523,0.662751,0.532397,0.085111,0.215135,36964.0
1,00000000000000000133,34.924404,21.757747,34.978955,35.016955,21.911980,21.85244,0.221502,0.248659,0.227048,0.208602,0.204732,0.164859,0.173744,0.212203,7.995815e+06,48441012200,535.962751,529.449501,532.223446,533.762669,1.598146e+06,4.970526e+07,3.646100e+06,4.279068e+07,1.322474e+06,2.264740e+07,41.7423,22.614651,41.693683,42.363243,22.925598,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.054552,0.154233,-0.048617,0.310947,0.199873,0.456001,0.165396,27008.0
2,00000000000000000134,34.924404,21.757747,34.925510,35.016955,21.900347,21.85244,0.217811,0.247611,0.227048,0.222031,0.204732,0.154968,0.173744,0.212203,1.301622e+06,48441012100,535.962751,531.698485,531.698485,533.762669,3.897641e+05,4.970526e+07,5.920586e+05,4.279068e+07,2.398845e+05,2.264740e+07,41.7423,22.614651,40.512643,42.363243,22.430844,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.001106,0.142600,-1.229657,-0.183807,0.299445,0.454862,0.184297,NaN
3,00000000000000000135,34.924404,21.757747,35.190528,35.016955,22.110893,21.85244,0.235294,0.243688,0.227048,0.217764,0.204732,0.189559,0.173744,0.212203,1.827807e+06,48441011900,535.962751,529.895505,529.895505,533.762669,9.567481e+05,4.970526e+07,1.491961e+05,4.279068e+07,3.368867e+05,2.264740e+07,41.7423,22.614651,43.857052,42.363243,23.956061,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.266125,0.353146,2.114752,1.341409,0.523440,0.081626,0.184312,31927.0
4,00000000000000000323,34.924404,21.757747,35.108325,35.016955,22.096334,21.85244,0.215404,0.220232,0.227048,0.217527,0.204732,0.188800,0.173744,0.212203,2.746964e+06,48441012300,535.962751,538.201497,538.201497,533.762669,1.386262e+06,4.970526e+07,4.748822e+05,4.279068e+07,4.949957e+05,2.264740e+07,41.7423,22.614651,43.410609,42.363243,23.800659,22.962161,280,"Abilene, TX","Abilene, TX Urbanized Area","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.183921,0.338587,1.668309,1.186008,0.504653,0.172875,0.180197,31449.0

In [19]:
data.groupby('Coastal?')['Median Income'].describe()

,count,mean,std,min,25%,50%,75%,max
Coastal?,,,,,,,,
False,32786.0,46924.478466,17773.250979,2500.0,35150.50,42907.0,53874.50,227596.0
True,22304.0,53660.255022,24714.035671,2500.0,36196.75,48750.0,64945.25,250000.0

## Check Missing Values

In [22]:
pd.DataFrame({'# Missing': data.isna().sum(), 
              '% Missing': (data.isna().sum() / len(data)) * 100})

                             # Missing  % Missing
system:index                         0   0.000000
AT_rur_day_summer                  249   0.445669
AT_rur_night_summer                249   0.445669
AT_urb_day_CT_act_summer           441   0.789318
AT_urb_day_all_summer              249   0.445669
AT_urb_night_CT_act_summer         441   0.789318
AT_urb_night_all_summer            249   0.445669
Albedo                             729   1.304791
Albedo_Built                       783   1.401443
Albedo_Built_all                     0   0.000000
Albedo_Grass                      1684   3.014086
Albedo_Grass_all                     0   0.000000
Albedo_Tree                        842   1.507043
Albedo_Tree_all                      0   0.000000
Albedo_all                           0   0.000000
Area                                 0   0.000000
Census_geoid                         0   0.000000
DEM_rur                              0   0.000000
DEM_urb_CT                          12   0.021478
DEM_urb_CT_act                       0   0.000000
DEM_urb_all                          0   0.000000
ESABuilt                             0   0.000000
ESABuilt_all                         0   0.000000
ESAGrass                             0   0.000000
ESAGrass_all                         0   0.000000
ESATree                              0   0.000000
ESATree_all                          0   0.000000
LST_rur_day_summer                   0   0.000000
LST_rur_night_summer                 0   0.000000
LST_urb_day_CT_act_summer          189   0.338279
LST_urb_day_all_summer               0   0.000000
LST_urb_night_CT_act_summer        189   0.338279
LST_urb_night_all_summer             0   0.000000
Urban_geoid                          0   0.000000
Urban_name                           0   0.000000
Urban_name_extended                  0   0.000000
.geo                                 0   0.000000
Clim_zone                          268   0.479676
Coastal?                           268   0.479676
LatLon                             268   0.479676
CUHI_day_summer                    441   0.789318
CUHI_night_summer                  441   0.789318
SUHI_day_summer                    189   0.338279
SUHI_night_summer                  189   0.338279
ESABuilt_Area                        0   0.000000
ESAGrass_Area                        0   0.000000
ESATree_Area                         0   0.000000
Median Income                      522   0.934295

## Descriptive Statistics

In [23]:
variables = ['CUHI_day_summer', 'CUHI_night_summer', 
             'SUHI_day_summer', 'SUHI_night_summer', 
             'ESABuilt_Area', 'ESAGrass_Area', 'ESATree_Area', 
             'Albedo_Built', 'Albedo_Grass', 'Albedo_Tree', 'DEM_urb_CT_act', 'Median Income']

In [24]:
data[variables].describe()

,CUHI_day_summer,CUHI_night_summer,SUHI_day_summer,SUHI_night_summer,ESABuilt_Area,ESAGrass_Area,ESATree_Area,Albedo_Built,Albedo_Grass,Albedo_Tree,DEM_urb_CT_act,Median Income
count,55430.000000,55430.000000,55682.000000,55682.000000,55871.000000,55871.000000,55871.000000,55088.000000,54187.000000,55029.000000,55871.000000,55349.000000
mean,0.264639,0.329187,1.971048,0.703809,0.359037,0.138873,0.380735,0.188033,0.187101,0.160474,216.757682,49649.746210
std,0.696411,0.556549,3.001631,0.979727,0.278373,0.120444,0.253447,0.031560,0.020886,0.017561,318.578435,21093.896548
min,-9.735958,-8.581393,-15.992810,-7.972859,0.000000,0.000000,0.000000,0.069045,0.027129,0.042494,-41.236906,2500.000000
25%,-0.027906,0.007505,-0.152277,0.032012,0.121453,0.046529,0.151364,0.167373,0.174631,0.150314,31.930661,35562.000000
50%,0.225942,0.297526,1.971115,0.736273,0.293530,0.111983,0.368969,0.184307,0.183649,0.158985,144.358247,45000.000000
75%,0.551160,0.643960,4.090334,1.370602,0.555940,0.200768,0.586754,0.204109,0.195420,0.168495,255.229190,58429.000000
max,4.922930,2.973430,12.746782,6.246033,1.000846,0.962560,0.988708,1.269241,0.496326,0.534201,2850.481011,250000.000000

## Save the CSV File

In [25]:
data.to_csv('data/data.csv', index=False)

## Prepare the Shapefile

In [26]:
import os
os.environ['USE_PYGEOS'] = '0'
import geopandas as gpd

In [27]:
gdf = gpd.read_file('data/usa/usa.shp')

In [28]:
gdf['SF'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming', 'Puerto Rico',
       'American Samoa', 'Guam', 'Northern Mariana Islands',
       'Virgin Islands'], dtype=object)

In [29]:
gdf_contiguous = gdf[['GEOID10', 'SF', 'CF', 'geometry']]
exclude = ['Alaska', 'Hawaii', 'Puerto Rico', 'American Samoa', 
           'Guam', 'Northern Mariana Islands', 'Virgin Islands']
gdf_contiguous = gdf_contiguous[~gdf_contiguous['SF'].isin(exclude)]
gdf_contiguous['GEOID10'] = gdf_contiguous['GEOID10'].astype(int)

In [30]:
len(gdf_contiguous)

72539

In [31]:
gdf_contiguous.head()

,GEOID10,SF,CF,geometry
0,1073001100,Alabama,Jefferson County,"POLYGON ((-86.88244 33.55233, -86.88187 33.552..."
1,1073001400,Alabama,Jefferson County,"POLYGON ((-86.84088 33.52759, -86.83782 33.528..."
2,1073002000,Alabama,Jefferson County,"POLYGON ((-86.71390 33.53930, -86.71435 33.539..."
3,1073003802,Alabama,Jefferson County,"POLYGON ((-86.90317 33.47177, -86.90284 33.472..."
4,1073004000,Alabama,Jefferson County,"POLYGON ((-86.85463 33.48754, -86.85554 33.486..."

In [32]:
gdf_contiguous.SF.unique()

array(['Alabama', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia', 'Florida',
       'Georgia', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

In [33]:
# Shapefile columns names cannot exceed 10 characters
columns = {'AT_rur_day_summer': 'ATrurday', 'AT_rur_night_summer': 'ATrurnight',
           'AT_urb_day_CT_act_summer': 'ATurbday', 'AT_urb_night_CT_act_summer':'ATurbnight',
           'Albedo_Built': 'AlbedBuilt', 'Albedo_Grass': 'AlbedGrass',
           'Albedo_Tree': 'AlbedoTree', 'Albedo':'Albedo', 'Census_geoid': 'GEOID10',
           'ESABuilt': 'ESABuilt', 'ESAGrass': 'ESAGrass', 'ESATree': 'ESATree',
           'LST_rur_day_summer': 'LSTrurday', 'LST_rur_night_summer': 'LSTrurnigh',
           'LST_urb_day_CT_act_summer': 'LSTurbday', 'LST_urb_night_CT_act_summer': 'LSTurbnigh',
           'Urban_geoid': 'Urban_geoid', 'CUHI_day_summer': 'CUHIday', 'CUHI_night_summer':'CUHInight',
           'SUHI_day_summer':'SUHIday', 'SUHI_night_summer':'SUHInight', 
           'ESABuilt_Area': 'BuiltArea', 'ESAGrass_Area': 'GrassArea', 'ESATree_Area': 'TreeArea',
           'DEM_urb_CT_act': 'DEMurb'}

In [35]:
drop_cols = ['system:index', 'AT_urb_day_all_summer', 'AT_urb_night_all_summer', 
             'Albedo_all', 'Albedo_Tree_all', 'Albedo_Built_all', 'Albedo_Grass_all',
             'DEM_rur', 'DEM_urb_CT', 'DEM_urb_all', 'ESABuilt_all', 'ESAGrass_all', 'ESATree_all',
             'LST_urb_day_all_summer', 'LST_urb_night_all_summer', 'Urban_name_extended']
data10 = data.drop(columns=drop_cols)
data10.rename(columns=columns, inplace=True)

In [36]:
shape_data = gdf_contiguous.merge(data10, how='right', on='GEOID10')

In [37]:
len(shape_data)

55871

In [38]:
shape_data.head()

,GEOID10,SF,CF,geometry,ATrurday,ATrurnight,ATurbday,ATurbnight,Albedo,AlbedBuilt,AlbedGrass,AlbedoTree,Area,DEMurb,ESABuilt,ESAGrass,ESATree,LSTrurday,LSTrurnigh,LSTurbday,LSTurbnigh,Urban_geoid,Urban_name,.geo,Clim_zone,Coastal?,LatLon,CUHIday,CUHInight,SUHIday,SUHInight,BuiltArea,GrassArea,TreeArea,Median Income
0,48441011400,Texas,Taylor County,"POLYGON ((-99.78711 32.43697, -99.78710 32.437...",34.924404,21.757747,35.112454,21.933739,0.214670,0.222724,0.215284,0.180942,3.612190e+06,531.262001,1.923120e+06,3.074373e+05,7.771083e+05,41.7423,22.614651,43.351823,23.277403,280,"Abilene, TX","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.188050,0.175992,1.609523,0.662751,0.532397,0.085111,0.215135,36964.0
1,48441012200,Texas,Taylor County,"POLYGON ((-99.72519 32.41558, -99.72519 32.415...",34.924404,21.757747,34.978955,21.911980,0.221502,0.248659,0.208602,0.164859,7.995815e+06,532.223446,1.598146e+06,3.646100e+06,1.322474e+06,41.7423,22.614651,41.693683,22.925598,280,"Abilene, TX","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.054552,0.154233,-0.048617,0.310947,0.199873,0.456001,0.165396,27008.0
2,48441012100,Texas,Taylor County,"POLYGON ((-99.71658 32.41600, -99.71728 32.416...",34.924404,21.757747,34.925510,21.900347,0.217811,0.247611,0.222031,0.154968,1.301622e+06,531.698485,3.897641e+05,5.920586e+05,2.398845e+05,41.7423,22.614651,40.512643,22.430844,280,"Abilene, TX","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.001106,0.142600,-1.229657,-0.183807,0.299445,0.454862,0.184297,NaN
3,48441011900,Texas,Taylor County,"POLYGON ((-99.72645 32.43473, -99.72676 32.431...",34.924404,21.757747,35.190528,22.110893,0.235294,0.243688,0.217764,0.189559,1.827807e+06,529.895505,9.567481e+05,1.491961e+05,3.368867e+05,41.7423,22.614651,43.857052,23.956061,280,"Abilene, TX","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.266125,0.353146,2.114752,1.341409,0.523440,0.081626,0.184312,31927.0
4,48441012300,Texas,Taylor County,"POLYGON ((-99.74236 32.41813, -99.74237 32.416...",34.924404,21.757747,35.108325,22.096334,0.215404,0.220232,0.217527,0.188800,2.746964e+06,538.201497,1.386262e+06,4.748822e+05,4.949957e+05,41.7423,22.614651,43.410609,23.800659,280,"Abilene, TX","{""type"":""MultiPoint"",""coordinates"":[]}",Temperate,False,"{""type"":""Point"",""coordinates"":[-99.90515446504...",0.183921,0.338587,1.668309,1.186008,0.504653,0.172875,0.180197,31449.0

In [40]:
shape_data.to_file('data/shapefile/uhi.shp')

<ipython-input-40-2cd633f60abb>:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  shape_data.to_file('data/shapefile/uhi.shp')

In [39]:
pd.DataFrame({'# Missing': shape_data.isna().sum(), 
              '% Missing': (shape_data.isna().sum() / len(shape_data)) * 100})

               # Missing  % Missing
GEOID10                0   0.000000
SF                  1187   2.124537
CF                  1187   2.124537
geometry            1234   2.208659
ATrurday             249   0.445669
ATrurnight           249   0.445669
ATurbday             441   0.789318
ATurbnight           441   0.789318
Albedo               729   1.304791
AlbedBuilt           783   1.401443
AlbedGrass          1684   3.014086
AlbedoTree           842   1.507043
Area                   0   0.000000
DEMurb                 0   0.000000
ESABuilt               0   0.000000
ESAGrass               0   0.000000
ESATree                0   0.000000
LSTrurday              0   0.000000
LSTrurnigh             0   0.000000
LSTurbday            189   0.338279
LSTurbnigh           189   0.338279
Urban_geoid            0   0.000000
Urban_name             0   0.000000
.geo                   0   0.000000
Clim_zone            268   0.479676
Coastal?             268   0.479676
LatLon               268   0.479676
CUHIday              441   0.789318
CUHInight            441   0.789318
SUHIday              189   0.338279
SUHInight            189   0.338279
BuiltArea              0   0.000000
GrassArea              0   0.000000
TreeArea               0   0.000000
Median Income        522   0.934295